Get grid certificates from Bitwarden

diff --git a/dot_bash_funcs b/dot_bash_funcs
--- a/dot_bash_funcs
+++ b/dot_bash_funcs
@@ -38,3 +38,49 @@ function lcg-view-setup() {
     . /cvmfs/sft.cern.ch/lcg/views/setupViews.sh "$release" "$arch_os_compiler"	
 
 }
+
+export -f lcg-view-setup
+
+function bw-session() {
+
+    if [[ ! "$(bw status)" =~ \"status\":\"([^\"]+)\" ]]; then
+        echo "ERROR: Cannot get BitWarden status. rc = $?" >&2
+        return
+    fi
+    case ${BASH_REMATCH[1]} in
+        'locked') 
+            export BW_SESSION=$(bw unlock --raw)
+            ;;
+        'unlocked')
+            echo "INFO: Bitwarden already unlocked." >&2
+            ;;
+        *) 
+            echo "ERROR: Bitwarden in unexpected state ${BASH_REMATCH[1]}"
+            ;;
+    esac
+}
+
+export -f bw-session
+
+function rucio-setup() {
+    
+    # clip has no python3
+    local release=$(lsb_release -rs)
+    set -- ${release//./ }
+    if [[ $1 == "7" && ! -f /usr/bin/python3 ]]; then
+        set --
+        . /cvmfs/cms.cern.ch/rucio/setup-py2.sh
+    else
+        set --
+        . /cvmfs/cms.cern.ch/rucio/setup-py2.sh
+    fi
+
+}
+
+export -f rucio-setup
+
+function crab-setup() {
+    . /cvmfs/cms.cern.ch/crab3/crab.sh
+}
+
+export -f crab-setup
